name: mami_q
description: "MamiQ - Comprehensive Prenatal Care Application"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.2
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  
  # Database & Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.3
  path: ^1.9.0
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.2
  firebase_analytics: ^11.3.3
  
  # UI & Navigation
  go_router: ^14.6.2
  flutter_screenutil: ^5.9.3
  animated_bottom_navigation_bar: ^1.3.3
  flutter_staggered_animations: ^1.1.1
  
  # Location & Maps
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  
  # Charts & Visualization
  fl_chart: ^0.69.0
  syncfusion_flutter_charts: ^27.1.57
  
  # HTTP & API
  http: ^1.2.2
  dio: ^5.7.0
  
  # Image & Media
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  cached_network_image: ^3.4.1
  
  # Notifications
  flutter_local_notifications: ^18.0.1
  
  # Forms & Validation
  flutter_form_builder: ^9.4.1
  form_builder_validators: ^11.0.0
  
  # Date & Time
  intl: ^0.19.0
  table_calendar: ^3.1.2
  timezone: ^0.9.4
  
  # Health & Wearables
  health: ^10.2.0
  
  # Utils
  uuid: ^4.5.1
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.0.5
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1
  share_plus: ^10.0.2
  flutter_html: ^3.0.0-beta.2
  maps_launcher: ^2.2.0
  google_sign_in: ^6.1.0
  
  # Animation
  lottie: ^3.1.2
  shimmer: ^3.0.0
  
  # PDF & Documents
  pdf: ^3.11.1
  printing: ^5.13.2
  
  # Security
  crypto: ^3.0.5
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/data/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
