// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3pIOQbVgKcekARb52V1dBZkfT0P-ifNA',
    appId: '1:953733671937:web:74fe94c3fabc224a48e400',
    messagingSenderId: '953733671937',
    projectId: 'mami-76cdd',
    authDomain: 'mami-76cdd.firebaseapp.com',
    storageBucket: 'mami-76cdd.firebasestorage.app',
    measurementId: 'G-ZGZXG0GVN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtSHze3iPY8TnUgwbXdLXE6Ru9MB_vzbM',
    appId: '1:953733671937:android:54efd3e95cb7388b48e400',
    messagingSenderId: '953733671937',
    projectId: 'mami-76cdd',
    storageBucket: 'mami-76cdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0FRgw0ImGkbVBWx-scIuh-0sCcNie9aE',
    appId: '1:953733671937:ios:ca02415eef90334648e400',
    messagingSenderId: '953733671937',
    projectId: 'mami-76cdd',
    storageBucket: 'mami-76cdd.firebasestorage.app',
    iosBundleId: 'com.example.mamiq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0FRgw0ImGkbVBWx-scIuh-0sCcNie9aE',
    appId: '1:953733671937:ios:ca02415eef90334648e400',
    messagingSenderId: '953733671937',
    projectId: 'mami-76cdd',
    storageBucket: 'mami-76cdd.firebasestorage.app',
    iosBundleId: 'com.example.mamiq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3pIOQbVgKcekARb52V1dBZkfT0P-ifNA',
    appId: '1:953733671937:web:f38548ef61b51a1248e400',
    messagingSenderId: '953733671937',
    projectId: 'mami-76cdd',
    authDomain: 'mami-76cdd.firebaseapp.com',
    storageBucket: 'mami-76cdd.firebasestorage.app',
    measurementId: 'G-XDT466RTGN',
  );
}
